/**
 * generated by Xtext 2.23.0
 */
package de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parametrized Collection Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.ParametrizedCollectionMethod#getTypeSelect <em>Type Select</em>}</li>
 *   <li>{@link de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.ParametrizedCollectionMethod#getIndexExpression <em>Index Expression</em>}</li>
 * </ul>
 *
 * @see de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.QuerydslPackage#getParametrizedCollectionMethod()
 * @model
 * @generated
 */
public interface ParametrizedCollectionMethod extends CollectionMethod
{
  /**
   * Returns the value of the '<em><b>Type Select</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Select</em>' attribute.
   * @see #setTypeSelect(String)
   * @see de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.QuerydslPackage#getParametrizedCollectionMethod_TypeSelect()
   * @model
   * @generated
   */
  String getTypeSelect();

  /**
   * Sets the value of the '{@link de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.ParametrizedCollectionMethod#getTypeSelect <em>Type Select</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Select</em>' attribute.
   * @see #getTypeSelect()
   * @generated
   */
  void setTypeSelect(String value);

  /**
   * Returns the value of the '<em><b>Index Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index Expression</em>' containment reference.
   * @see #setIndexExpression(Expression)
   * @see de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.QuerydslPackage#getParametrizedCollectionMethod_IndexExpression()
   * @model containment="true"
   * @generated
   */
  Expression getIndexExpression();

  /**
   * Sets the value of the '{@link de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.ParametrizedCollectionMethod#getIndexExpression <em>Index Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index Expression</em>' containment reference.
   * @see #getIndexExpression()
   * @generated
   */
  void setIndexExpression(Expression value);

} // ParametrizedCollectionMethod
