<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="commands" nsURI="http://www.mpw.uni-stuttgart.de/commands" nsPrefix="commands">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="In this package the metamodel for commands and its related roles like Entity or CommandStack are defined. Commands are the meta-type for behavior in a MPW."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveCommand" abstract="true" eSuperTypes="#//Command">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines a primitive command which can set, add or removes values regarding to a property of an Entity."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="ecore:EClass BaseTypes.ecore#//Entity">
      <eAnnotations source="sharedOwnership"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetPropertyCommand" eSuperTypes="#//PrimitiveCommand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A primitive command which sets a generic value (Object) to a property."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" eType="ecore:EDataType BaseTypes.ecore#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" eType="ecore:EDataType BaseTypes.ecore#//Object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddEntityCommand" eSuperTypes="#//PrimitiveCommand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A primitive command which adds an entity to a collection property."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityToAdd" lowerBound="1"
        eType="ecore:EClass BaseTypes.ecore#//Entity">
      <eAnnotations source="sharedOwnership"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveEntityCommand" eSuperTypes="#//PrimitiveCommand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A primitive command which removes an entity from a collection property."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityToRemove" lowerBound="1"
        eType="ecore:EClass BaseTypes.ecore#//Entity">
      <eAnnotations source="sharedOwnership"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandStack" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Tracks the executed Commands which allow to undo and redo their behavior."/>
    </eAnnotations>
    <eOperations name="execute">
      <eParameters name="command" eType="#//Command"/>
    </eOperations>
    <eOperations name="undo"/>
    <eOperations name="redo"/>
    <eOperations name="undoAll"/>
    <eOperations name="redoAll"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stack" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the basic type for PrimitiveCommand or CompositeCommand which represent behavior which can be executed. It provides the ability to: execute, undo or redo.&#xD;&#xA;&#xD;&#xA;Commands are processed in context of an Actor or the Stage."/>
    </eAnnotations>
    <eOperations name="execute"/>
    <eOperations name="undo"/>
    <eOperations name="redo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeCommand" abstract="true" eSuperTypes="#//Command">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A more complex type of commands which makes use of multiple sub-commands. Usually the sub-commands are PrimitiveCommands.&#xD;&#xA;&#xD;&#xA;Example Hamster-Simulation: Game commands: Move, PickGrain, PutGrain or TurnLeft. Editor commands: InitTerritory or InitHamster."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCommands" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameCommandStack" eSuperTypes="#//CommandStack">
    <eOperations name="startGame"/>
    <eOperations name="startGamePaused"/>
    <eOperations name="pause"/>
    <eOperations name="resume"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semaphore" lowerBound="1"
        eType="ecore:EDataType BaseTypes.ecore#//Semaphore" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//Mode" defaultValueLiteral="INITIALIZING"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditorCommandStack" eSuperTypes="#//CommandStack"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Mode">
    <eLiterals name="RUNNING"/>
    <eLiterals name="INITIALIZING" value="1"/>
    <eLiterals name="STOPPED" value="2"/>
    <eLiterals name="PAUSED" value="3"/>
  </eClassifiers>
</ecore:EPackage>
