<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mpw" nsURI="http://www.mpw.uni-stuttgart.de/mpw" nsPrefix="mpw">
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true" eSuperTypes="#//TileContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prop" abstract="true" eSuperTypes="#//TileContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tile" eSuperTypes="BaseTypes.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//TileContent" eOpposite="#//TileContent/currentTile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="south" eType="#//Tile"
        eOpposite="#//Tile/north"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="north" eType="#//Tile"
        eOpposite="#//Tile/south"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="east" eType="#//Tile" eOpposite="#//Tile/west"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="west" eType="#//Tile" eOpposite="#//Tile/east"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stage" eType="#//Stage"
        derived="true" eOpposite="#//Stage/tiles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TileContent" abstract="true" eSuperTypes="BaseTypes.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentTile" eType="#//Tile"
        eOpposite="#//Tile/contents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stage" eType="#//Stage"
        eOpposite="#//Stage/tileContents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage" abstract="true" eSuperTypes="BaseTypes.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiles" upperBound="-1"
        eType="#//Tile" containment="true" eOpposite="#//Tile/stage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tileContents" upperBound="-1"
        eType="#//TileContent" containment="true" eOpposite="#//TileContent/stage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stageSize" lowerBound="1"
        eType="#//Size" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MiniProgrammingWorld" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stage" lowerBound="1" eType="#//Stage"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editorCommandStack" lowerBound="1"
        eType="ecore:EClass Command.ecore#//CommandStack" changeable="false" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performance" lowerBound="1"
        eType="#//GamePerformance" changeable="false" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameLog" lowerBound="1"
        eType="#//GameLog" changeable="false" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userInputInterface" lowerBound="1"
        eType="#//UserInputInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="stereotypes/MpwStereotypes.ecore#//ValueType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="NORTH"/>
    <eLiterals name="SOUTH" value="1"/>
    <eLiterals name="WEST" value="2"/>
    <eLiterals name="EAST" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserInputInterface" abstract="true"
      interface="true" eSuperTypes="stereotypes/MpwStereotypes.ecore#//Dependency">
    <eOperations name="readInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="confirmAlert">
      <eParameters name="t" eType="ecore:EDataType BaseTypes.ecore#//Throwable"/>
    </eOperations>
    <eOperations name="abort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameLog">
    <eOperations name="write">
      <eParameters name="actor" eType="#//Actor"/>
      <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logEntries" upperBound="-1"
        eType="#//LogEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Size" eSuperTypes="stereotypes/MpwStereotypes.ecore#//ValueType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnCount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of (max.) columns in this size object."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowCount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of (max.) rows in this size object."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" eType="#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamePerformance">
    <eOperations name="startGame"/>
    <eOperations name="startGamePaused"/>
    <eOperations name="pauseGame"/>
    <eOperations name="resumeGame"/>
    <eOperations name="stopGame"/>
    <eOperations name="hardReset"/>
    <eOperations name="abortOrStopGame"/>
    <eOperations name="preExecuteGameCommand"/>
    <eOperations name="delayControlFlow"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semaphore" lowerBound="1"
        eType="ecore:EDataType BaseTypes.ecore#//Semaphore" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" lowerBound="1" eType="#//Mode"
        defaultValueLiteral="INITIALIZING"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="4.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delayEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameCommandStack" lowerBound="1"
        eType="ecore:EClass Command.ecore#//CommandStack" changeable="false" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mode">
    <eLiterals name="RUNNING"/>
    <eLiterals name="INITIALIZING" value="1"/>
    <eLiterals name="STOPPED" value="2"/>
    <eLiterals name="PAUSED" value="3"/>
    <eLiterals name="ABORTED" value="4"/>
  </eClassifiers>
</ecore:EPackage>
