<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="viewmodel" nsURI="http://www.mpw.uni-stuttgart.de/viewmodel"
    nsPrefix="viewmodel">
  <eClassifiers xsi:type="ecore:EClass" name="GameViewModel" eSuperTypes="stereotypes/ViewModelStereotypes.ecore#//ViewModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Datastructure with Databinding capabilities which contains all relevant information to be displayed on the screen."/>
    </eAnnotations>
    <eOperations name="getCellAt" eType="#//ViewModelCell">
      <eAnnotations source="const"/>
      <eParameters name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="init">
      <eParameters name="size" eType="ecore:EClass MiniProgrammingWorld.ecore#//Size"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//ViewModelRow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logEntries" upperBound="-1"
        eType="#//ViewModelLogEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="ecore:EClass MiniProgrammingWorld.ecore#//Size"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameViewInput" abstract="true" interface="true">
    <eOperations name="playClicked"/>
    <eOperations name="pauseClicked"/>
    <eOperations name="undoClicked"/>
    <eOperations name="redoClicked"/>
    <eOperations name="textTyped">
      <eParameters name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="close"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameViewPresenter" eSuperTypes="#//GameViewInput stereotypes/ViewModelStereotypes.ecore#//Presenter">
    <eOperations name="bind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewModel" lowerBound="1"
        eType="#//GameViewModel" changeable="false" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semaphore" eType="ecore:EDataType BaseTypes.ecore#//Semaphore"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewModelCell" eSuperTypes="stereotypes/ViewModelStereotypes.ecore#//ViewModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//ViewModelCellLayer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="ecore:EClass MiniProgrammingWorld.ecore#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewModelRow" eSuperTypes="stereotypes/ViewModelStereotypes.ecore#//ViewModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//ViewModelCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewModelCellLayer" eSuperTypes="stereotypes/ViewModelStereotypes.ecore#//ViewModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewModelLogEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="BLACK"/>
    <eLiterals name="BLUE" value="1"/>
    <eLiterals name="GREEN" value="2"/>
    <eLiterals name="YELLOW" value="3"/>
    <eLiterals name="PINK" value="4"/>
    <eLiterals name="MAGENTA" value="5"/>
    <eLiterals name="RED" value="6"/>
  </eClassifiers>
</ecore:EPackage>
