/*
 * generated by Xtext 2.23.0
 */
package de.unistuttgart.iste.sqa.mpw.modeling.queries.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.unistuttgart.iste.sqa.mpw.modeling.queries.QueryDslRuntimeModule;
import de.unistuttgart.iste.sqa.mpw.modeling.queries.QueryDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QueryDslIdeSetup extends QueryDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QueryDslRuntimeModule(), new QueryDslIdeModule()));
	}
	
}
