#ifndef DE_UNISTUTTGART_ISTE_SQA_MPW_FRAMEWORK_STAGEFAKE_H
#define DE_UNISTUTTGART_ISTE_SQA_MPW_FRAMEWORK_STAGEFAKE_H

#include "Stage.h"

namespace mpw {

	class StageFake : public Stage {

	};

}

#endif //DE_UNISTUTTGART_ISTE_SQA_MPW_FRAMEWORK_STAGEFAKE_H
