/*
 * generated by Xtext 2.23.0
 */
package de.unistuttgart.iste.sqa.mpw.modeling.querydsl.validation;

import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;

import de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.OldValueExpression;
import de.unistuttgart.iste.sqa.mpw.modeling.querydsl.querydsl.Postcondition;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class QueryDslValidator extends AbstractQueryDslValidator {
	
	@Check
	public void oldValuesOnlyUsedInPostConditions(OldValueExpression statement) {
		if (EcoreUtil2.getContainerOfType(statement, Postcondition.class) == null) {
			error("Old value expressions are only allowed in postconditions", null);
		}
	}
}
