<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generationAnnotations" nsURI="http://www.mpw.uni-stuttgart.de/generation/annotations"
    nsPrefix="generationAnnotations">
  <eClassifiers xsi:type="ecore:EClass" name="GenerationAnnotation" abstract="true"
      eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorAnnotation" eSuperTypes="#//GenerationAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="FieldAssignmentAnnotation" abstract="true"
      eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFeature" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterToFieldAssignmentAnnotation"
      eSuperTypes="#//FieldAssignmentAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyPathFieldAssignmentAnnotation"
      eSuperTypes="#//FieldAssignmentAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldInitializationAnnotation" abstract="true"
      eSuperTypes="#//GenerationAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="InlineSimpleFieldInitializationAnnotation"
      eSuperTypes="#//FieldInitializationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterInputVariablePropertyPaths"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorSimpleFieldInitializationAnnotation"
      eSuperTypes="#//FieldInitializationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterInputVariablePropertyPaths"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constructorTypeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisibilityAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="#//Visibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="PRIVATE"/>
    <eLiterals name="PUBLIC" value="1"/>
    <eLiterals name="INTERNAL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandParameterCreationAnnotation"
      eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="ecore:EClass CommandBehaviors.ecore#//Transformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterMappings" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parametersVariableName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandCreationAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="ecore:EClass CommandBehaviors.ecore#//Transformation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandVariableName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="command"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parametersVariableName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandCallAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="ecore:EClass CommandBehaviors.ecore#//Transformation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetRoleVariableName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parametersVariableName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryCallAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" lowerBound="1" eType="ecore:EClass QueryBehaviors.ecore#//Query"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalRoleField" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetPropertyAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getterTypeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getterOperationName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetPropertyDeclarationAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldTypeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getterName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCallAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterInputVariablePropertyPaths"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyPathReturnAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportTypeAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeQualifiedTypeName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddVariableToCollectionAnnotation" eSuperTypes="#//GenerationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionPropertyPath"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="parameters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterPropertyPath"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableObjectConstructionAnnotation"
      eSuperTypes="#//FieldInitializationAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constructorTypeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterInputVariablePropertyPaths"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
