/*
 * generated by Xtext 2.23.0
 */
package de.unistuttgart.iste.sqa.mpw.modeling.querydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QueryDslUiModule extends AbstractQueryDslUiModule {

	public QueryDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
