<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="command" nsURI="http://www.hamster.uni-stuttgart.de/command"
    nsPrefix="command">
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveCommand" abstract="true" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetPropertyCommand" eSuperTypes="#//PrimitiveCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddEntityCommand" eSuperTypes="#//PrimitiveCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveEntityCommand" eSuperTypes="#//PrimitiveCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommandStack">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stack" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" interface="true">
    <eOperations name="execute"/>
    <eOperations name="undo"/>
    <eOperations name="redo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeCommand" abstract="true" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCommands" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
