<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mpw" nsURI="http://www.mpw.uni-stuttgart.de/mpw" nsPrefix="mpw">
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true" eSuperTypes="#//TileContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandStack" lowerBound="1"
        eType="ecore:EClass Command.ecore#//CommandStack"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prop" abstract="true" eSuperTypes="#//TileContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tile" eSuperTypes="Command.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//TileContent" eOpposite="#//TileContent/currentTile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TileContent" abstract="true" eSuperTypes="Command.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentTile" eType="#//Tile"
        eOpposite="#//Tile/contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage" abstract="true" eSuperTypes="Command.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiles" upperBound="-1"
        eType="#//Tile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandStack" lowerBound="1"
        eType="ecore:EClass Command.ecore#//CommandStack"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tileContents" upperBound="-1"
        eType="#//TileContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MiniProgrammingWorld" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stage" lowerBound="1" eType="#//Stage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandStack" lowerBound="1"
        eType="ecore:EClass Command.ecore#//CommandStack" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="NORTH"/>
    <eLiterals name="SOUTH" value="1"/>
    <eLiterals name="WEST" value="2"/>
    <eLiterals name="EAST" value="3"/>
  </eClassifiers>
</ecore:EPackage>
