<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mpw" nsURI="http://www.mpw.uni-stuttgart.de/mpw" nsPrefix="mpw">
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true" eSuperTypes="#//TileContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandstack" lowerBound="1"
        eType="#//command/CommandStack"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prop" abstract="true" eSuperTypes="#//TileContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//TileContent" eOpposite="#//TileContent/currentTile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TileContent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentTile" eType="#//Tile"
        eOpposite="#//Tile/contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandstack" lowerBound="1"
        eType="#//command/CommandStack"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiles" upperBound="-1"
        eType="#//Tile" containment="true"/>
  </eClassifiers>
  <eSubpackages name="command">
    <eClassifiers xsi:type="ecore:EClass" name="CommandStack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="stack" upperBound="-1"
          eType="#//command/GameCommand" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EditorCommand" abstract="true" eSuperTypes="#//command/GameCommand"/>
    <eClassifiers xsi:type="ecore:EClass" name="GameCommand" abstract="true">
      <eOperations name="execute"/>
      <eOperations name="undo"/>
      <eOperations name="redo"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
