<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="viewmodel" nsURI="http://www.hamster.uni-stuttgart.de/viewmodel"
    nsPrefix="viewmodel">
  <eClassifiers xsi:type="ecore:EClass" name="ViewModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Datastructure with Databinding capabilities which contains all relevant information to be displayed on the screen."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiController" abstract="true" interface="true">
    <eOperations name="playClicked"/>
    <eOperations name="stopClicked"/>
    <eOperations name="textTyped">
      <eParameters name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Presenter" eSuperTypes="#//UiController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewModel" lowerBound="1"
        eType="#//ViewModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" lowerBound="1" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents the callback interface to the UI framework. Especially it receives the viewmodel to display the game state on the screen."/>
    </eAnnotations>
    <eOperations name="showViewModel">
      <eParameters name="viewModel" eType="#//ViewModel"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
