/*
 * generated by Xtext 2.23.0
 */
package de.unistuttgart.iste.sqa.mpw.modeling.queries;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QueryDslRuntimeModule extends AbstractQueryDslRuntimeModule {
}
