/*
 * generated by Xtext 2.23.0
 */
package de.unistuttgart.iste.sqa.mpw.modeling.querydsl.ide;


/**
 * Use this class to register ide components.
 */
public class QueryDslIdeModule extends AbstractQueryDslIdeModule {
}
