<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="viewmodelstereotypes" nsURI="http://www.mpw.uni-stuttgart.de/viewmodelstereotypes"
    nsPrefix="viewmodelstereotypes">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="In this package stereotypes are defined which are used in view models to classify roles like ViewModel datastructures or Presenter classes.&#xD;&#xA;&#xD;&#xA;Note: the stereotypes are only relevant for transformation / generation and in the generated target simulator they are not present."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Presenter" abstract="true" interface="true"
      eSuperTypes="#//ViewStereotype"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewModel" abstract="true" interface="true"
      eSuperTypes="#//ViewStereotype"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewStereotype" abstract="true" interface="true"/>
</ecore:EPackage>
